version: "3.1"

services:
  app:
    image: php:7.4-alpine
    command: php -S 0.0.0.0:8000 /app/src/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock